### ISSUE TITLE
Optimize the size of the cache

### ISSUE THREAD

**Issue by droped** [Wolvan/Homebr3w#10]
I know, the pics in the cache are extremely small and occupy little space but every bit is precious. Using [this](http://nikkhokkho.sourceforge.net/static.php?page=FileOptimizer) program, I was able to reduce the size of some pngs by 50%. I think it is worth doing it.

**Comment by Wolvan** [comment]
Not sure how much I can do client side here, might be something that TitleDB.com needs to make.
@ksanislo would it be possible to optimize the PNGs that you are creating on TitleDB?

**Comment by ksanislo** [comment]
In the upcoming backend rewrite, PNG images will be rendered in realtime from saved SMDH data. Increasing the compression level will directly impact the generation time, so I'm not sure it's worth the trade off on the server to save a handful of MB at the most. I'd actually figure most C based clients would be caching the uncompressed raw icon data and not using the .png at all.

**Comment by Wolvan** [comment]
I see. Unfortunately I can't really do much about compression in Lua alone. Any other ideas?

**Comment by ksanislo** [comment]
Nah, you'd be trading speed for storage space no matter what you do. The 3DS isn't super fast hardware to start with and big SD cards are cheap.

**Comment by Wolvan** [comment]
Good argument, I'd rather have the speed since the app is slow to start up already anyways. Marking as `Won't fix` and closing for now, unless @poutros has another idea.

**Comment by poutros** [comment]
That's ok. I can do it myself. It takes a few seconds at most.
