### ISSUE TITLE
[Enhancement] Better Descriptions

### ISSUE THREAD

**Issue by NULLx76** [Wolvan/Homebr3w#15]
The descriptions are a lot of the time just the name of the app and provide no useful information. I would love to see better descriptions for them.

**Comment by Wolvan** [comment]
This is actually neither Homebr3w's nor TitleDB.com's fault. TitleDB and thus also Homebr3w load the description directly from .cia. The .cia's are responsible to provide a fitting description, so you should ask the developers to add descriptions. Not really sure how ksanislo or me could help her.

Closing for now, reopening if there are ideas on how to fix this.

**Comment by NinjaBoyLao** [comment]
I mean if you wanted to you could just write a single file during the load process, where it does all the checks, that contains text descriptions of each .cia and then update that manually whenever new .cia's are added. Or maybe even just add an option to TitleDB for users to input a description of whatever project/homebrew/tool/whatever they're linking in, with a character limit or something, that way you don't even have to do anything.

**Comment by Wolvan** [comment]
@NinjaBoyLao for any changes to TitleDB you would need to ask @ksanislo. I am not sure but I think part of his rewrite actually has custom descriptions? If not, bug the people who made the homebrew to add one, since imo, it's on them to describe their apps in the first place
