### ISSUE TITLE
[Bug?] A corrupted looking app on Homebr3w

### ISSUE THREAD

**Issue by jackomix** [Wolvan/Homebr3w#17]
If you go into Homebr3w and just press up to go to the bottom you will see a program that looks like it's corrupted.

**Comment by Wolvan** [comment]
It's not corrupted, the .cia File for the app has been built wrong, see [this post on GBATemp](https://gbatemp.net/threads/release-homebr3w-simple-homebrew-browser-and-installer.434105/page-8#post-6633690)

The app is actually https://github.com/MichiS97/The-Real-Snake-3DS
