### ISSUE TITLE
Change app directory

### ISSUE THREAD

**Issue by sanxzkid** [Wolvan/Homebr3w#18]
Use some default folder like "/3ds/homebr3w" for a clean SD management

**Comment by Wolvan** [comment]
I'll change the data directory to `SDMC:/3ds/data/Homebr3w`. Is that OK?

**Comment by Wolvan** [comment]
https://wolvan.github.io/Homebr3w/build/
The new nightly should have a changed data directory, but is otherwise the same as the current release. You can use that until I made a proper release (which might take a while since I don't think a single change warrants a full release)
