### ISSUE TITLE
PHBank issue

### ISSUE THREAD

**Issue by x7l7j8cc** [Wolvan/Homebr3w#20]
Hi, I begin by saying that I have already solved this.
But, the Homebrew, when install the "PHBank"/"PHBank GB" doesnt install the "pk" folder too, so this will turn in error when opening the Bank.

Can you implement a script to extract the "pk" folder and place it on the root of the SD?

**Comment by Wolvan** [comment]
I don't want to sound like a jerk here, but honestly, this is something app devs should start to handle themselves, creating/downloading data they need to run I mean.

I'd gladly see about implementing this though if I had a way of determining if an app needs extra data, but alas, until TitleDB gives me that info I don't think there is much I can do.

Gonna mark this as `won't fix` for now, but keeping this open for a while longer in case people have ideas how to handle this.
