### ISSUE TITLE
Notification Bomb straight up isn't/Title ID issue

### ISSUE THREAD

**Issue by NinjaBoyLao** [Wolvan/Homebr3w#23]
Selecting Notification Bomb downloads 3DBFI, not Notification Bomb. Probably this is an issue on TitleDB's end but i don't know where to put this

**Comment by Wolvan** [comment]
@ksanislo 
![image](https://cloud.githubusercontent.com/assets/1437010/20030468/e39e0f82-a365-11e6-9227-04f9d1002892.png)
That's something for you. Gonna close this issue and mark as won't fix but feel free to discuss this further here
