### ISSUE TITLE
[TitleDB down]KEEP GETTING ERROR PLEASE HELP

### ISSUE THREAD

**Issue by xavier11991** [Wolvan/Homebr3w#29]
ok i keep receiving this error and I don't know what to do please help me.
error: [string "?"]:642: attempt to index a nil value (local 'timetoconvert')

**Comment by Wolvan** [comment]
If you check TitleDB.com, you can see that the backend is currently broken, aka Homebr3w (as well as FBI and TitleDB's interface) are unable to access the data. We need to wait on @ksanislo to get the system running again.

**Comment by xavier11991** [comment]
ok thanks man I was getting worried :)

**Comment by ksanislo** [comment]
Sorry about the downtime. It looks like it ran the VM out of memory, and was killed by OOM killer. Then systemd failed to restart things as it was supposed to. I've adjusted systemd to make sure it will always auto-restart from now on, but I suppose I'll need to pay for a RAM upgrade to fix it properly.

**Comment by Wolvan** [comment]
I see your problem. You're using systemd haha!
