### ISSUE TITLE
Tracking mtime on installed apps

### ISSUE THREAD

**Issue by ksanislo** [Wolvan/Homebr3w#3]
The mtime from TitleDB is currently the most accurate way to track revisions of apps since most home-brew don't currently have an actual version number in them. Many backend methods have some kind of time identifier, however basic HTTP links that don't provide a timestamp header will get the scan update time saved as mtime instead. Since it's a unix epoch timestamp (seconds since the start of 1970) so it /should/ always go up, but I've not checked everything to see if anything has invalid/future date or other bad data. Just being different than the previous install should be enough to say it's a new version.

**Comment by Wolvan** [comment]
Done! Finished in commit a951d605d47f00dda7030366c679d3e6d025109a, gonna be part of v1.2.0 after my Beta testers report back to me.
