### ISSUE TITLE
Console freezes when lid is closed when loading

### ISSUE THREAD

**Issue by Masamune3210** [Wolvan/Homebr3w#30]
1. Open app
2. Let it start loading
3. Close 3DS
4. Open 3DS
5. Screen wont turn back on, console won't respond until forced to shut off and restarted

**Comment by Wolvan** [comment]
Have you tried replicating this with any other Lua Player Plus App? o3ds or n3ds?
As far as I recall it is an issue with lpp, but I could be wrong here

**Comment by Masamune3210** [comment]
If you can name another, I can try it and report back,
Was unaware if it was an issue with the player or the app itself

**Comment by Wolvan** [comment]
CHMM2 for example

**Comment by Masamune3210** [comment]
I will check and get back to you when I get home

**Comment by Masamune3210** [comment]
It happens with CHMM2 as well, is there any way for me to let the dev know?

**Comment by Wolvan** [comment]
I mean, I think @Rinnegatamante already knows about this

**Comment by Masamune3210** [comment]
I wasn't sure, didnt know if they were on Github or not

**Comment by Wolvan** [comment]
I pinged him, so he should be seeing this issue

**Comment by Masamune3210** [comment]
I also posted on a similar issue on the repo, just found it

**Comment by Rinnegatamante** [comment]
That happens cause lpp-3ds doesn't perform any kind of suspension/resume of the app state.
It will require knowledge of ctrulib i completely lost/don't have. If you can point me to an homebrew that correctly works with lid closed/reopened, i can try to pick the useful code.

**Comment by Masamune3210** [comment]
TWLoader works correctly with closing the  lid

**Comment by Masamune3210** [comment]
So does freeshop, if you are still wondering
