### ISSUE TITLE
Can you alter your php backend from v1.0 to only list the upgraded version of Homebr3w itself?

### ISSUE THREAD

**Issue by ksanislo** [Wolvan/Homebr3w#4]
Just a random idea, but if you can change your intermediary php to only list one entry for Homebr3w itself, it would basically force people to upgrade to the new version.

**Comment by Wolvan** [comment]
Done! v1.0.0 now only shows Homebr3w (tested with the 3dsx build but the builds pull the applist from the same place anyways)
