### ISSUE TITLE
Failed to download library!

### ISSUE THREAD

**Issue by TheMrDew** [Wolvan/Homebr3w#8]
This is my first time using this app and I am using the .cia version.  When I boot it up, it gives me this messages as well as " Unable to continue, please try restarting the app and try again".  I have done this multiple times as well as turn the 3ds off and on again and still nothing.

**Comment by TheMrDew** [comment]
It started to work for unknown reasons.  I tried using the .3dsx, tried to update.  Said it did and when I loaded it again, it worked

**Comment by Wolvan** [comment]
It can depend on your internet, if that's finicky, Library download might fail. That's why it says try again.

**Comment by Wolvan** [comment]
This was indeed a bug, more precisely the `Homebr3w` directory missing when trying to download libraries. That is fixed now though.
