### ISSUE TITLE
Add option to uninstall app

### ISSUE THREAD

**Issue by droped** [Wolvan/Homebr3w#9]
Just like there is an option to install, launch... I think there should be an option to uninstall.

**Comment by Wolvan** [comment]
Should be do-able, if I find a button I can use for it. I kind of already used up most buttons, any suggestion?

**Comment by Masamune3210** [comment]
Perhaps use the select button to change modes or something?

**Comment by Wolvan** [comment]
Alright, Select now switches between uninstall and install mode for existing applications.
